### ISSUE TITLE
Error when building the project

### ISSUE THREAD

**Issue by caritos** [toedter/e4-tutorial#4]
This is the log when I run the command "mvn clean verify -X".
I am using Windows 7/Java 1.6 32 Bit.

```
!ENTRY org.eclipse.osgi 4 0 2014-01-11 03:02:17.834
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Bundle org.eclipse.e4.tutorial.contacts.views.details.test is not found
        at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundleClassLoader(OsgiSurefireBooter.java:149)
        at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:67)
        at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
An error has occurred. See the log file
C:\Users\carel06\git\e4-tutorial\org.eclipse.e4.tutorial.contacts.views.details.test\target\work\configuration\138942733
5553.log.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] org.eclipse.e4.tutorial.contacts.build.tycho ...... SUCCESS [0.250s]
[INFO] org.eclipse.e4.tutorial.contacts.model ............ SUCCESS [3.122s]
[INFO] org.eclipse.e4.tutorial.contacts.model.application  SUCCESS [3.198s]
[INFO] org.eclipse.e4.tutorial.contacts .................. SUCCESS [2.625s]
[INFO] org.eclipse.e4.tutorial.contacts.login ............ SUCCESS [2.752s]
[INFO] org.eclipse.e4.tutorial.contacts.model.simple ..... SUCCESS [1.781s]
[INFO] org.eclipse.e4.tutorial.contacts.logging .......... SUCCESS [1.618s]
[INFO] org.eclipse.e4.tutorial.contacts.renderer ......... SUCCESS [2.749s]
[INFO] org.eclipse.e4.tutorial.contacts.views.details .... SUCCESS [2.414s]
[INFO] org.eclipse.e4.tutorial.contacts.logging.config ... SUCCESS [1.511s]
[INFO] org.eclipse.e4.tutorial.contacts.feature .......... SUCCESS [0.905s]
[INFO] org.eclipse.e4.tutorial.contacts.product .......... SUCCESS [44.837s]
[INFO] org.eclipse.e4.tutorial.contacts.views.details.test  FAILURE [10.904s]
[INFO] kepler ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:34.146s
[INFO] Finished at: Sat Jan 11 03:02:22 EST 2014
[INFO] Final Memory: 23M/95M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.19.0:test (default-test) on project org.eclipse
.e4.tutorial.contacts.views.details.test: An unexpected error occured (return code 13). See log for details. -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0
.19.0:test (default-test) on project org.eclipse.e4.tutorial.contacts.views.details.test: An unexpected error occured (r
eturn code 13). See log for details.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: An unexpected error occured (return code 13). See log for deta
ls.
        at org.eclipse.tycho.surefire.TestMojo.runTest(TestMojo.java:970)
        at org.eclipse.tycho.surefire.TestMojo.execute(TestMojo.java:668)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.e4.tutorial.contacts.views.details.test
```

**Comment by toedter** [comment]
Hi caritos,

I have the same environment:
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17
Maven home: C:\java\apache-maven-3.1.1\bin..
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: C:\java\jdk1.7.0\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

I cloned a fresh repo, invoked  "mvn clean verify -X" and got

Reactor Summary:

org.eclipse.e4.tutorial.contacts.build.tycho ...... SUCCESS [0.271s]
org.eclipse.e4.tutorial.contacts.model ............ SUCCESS [4.088s]
org.eclipse.e4.tutorial.contacts.model.application  SUCCESS [1.176s]
org.eclipse.e4.tutorial.contacts .................. SUCCESS [0.413s]
org.eclipse.e4.tutorial.contacts.login ............ SUCCESS [0.555s]
org.eclipse.e4.tutorial.contacts.model.simple ..... SUCCESS [0.249s]
org.eclipse.e4.tutorial.contacts.renderer ......... SUCCESS [0.393s]
org.eclipse.e4.tutorial.contacts.views.details .... SUCCESS [0.283s]
org.eclipse.e4.tutorial.contacts.logging .......... SUCCESS [0.152s]
org.eclipse.e4.tutorial.contacts.logging.config ... SUCCESS [0.084s]
org.eclipse.e4.tutorial.contacts.feature .......... SUCCESS [0.142s]
org.eclipse.e4.tutorial.contacts.product .......... SUCCESS [36.113s]
org.eclipse.e4.tutorial.contacts.views.details.test  SUCCESS [5.865s]

## kepler ............................................ SUCCESS [0.014s]

## BUILD SUCCESS

Total time: 1:21.790s
Finished at: Thu Jan 23 06:58:50 CET 2014

## Final Memory: 51M/128M

Does the build still fail at your machine?
