### ISSUE TITLE
Error when running e4-tutorial.exe

### ISSUE THREAD

**Issue by caritos** [toedter/e4-tutorial#5]
When I try to run the e4-tutorial.exe in C:\git\e4-tutorial\org.eclipse.e4.tutorial.contacts.product\target\products\e4-tutorial\win32\win32\x86, I get the error message

```
!SESSION 2014-01-11 03:07:06.115 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_45
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86

!ENTRY org.eclipse.equinox.app 0 0 2014-01-11 03:07:06.765
!MESSAGE Product org.eclipse.e4.tutorial.contacts.product could not be found.

!ENTRY org.eclipse.osgi 2 0 2014-01-11 03:07:06.885
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.885
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.e4.tutorial.contacts.logging.config_1.0.0.201401110801.jar was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.logging.config 2 0 2014-01-11 03:07:06.885
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.885
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.e4.tutorial.contacts.model.application_1.0.0.201401110801.jar was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.model.application 2 0 2014-01-11 03:07:06.886
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.886
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.e4.tutorial.contacts.login_1.0.0.201401110801.jar was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.login 2 0 2014-01-11 03:07:06.886
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.886
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.e4.tutorial.contacts.logging_1.0.0.201401110801.jar was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.logging 2 0 2014-01-11 03:07:06.886
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

!ENTRY org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts_1.0.0.201401110801 [25] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing required bundle org.eclipse.e4.tutorial.contacts.model.application_1.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts.logging_1.0.0.201401110801 [26] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.logging 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts.logging.config_1.0.0.201401110801 [27] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.logging.config 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing host org.eclipse.e4.tutorial.contacts.logging_1.0.0.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.logging.config 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts.login_1.0.0.201401110801 [28] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.login 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts.model.application_1.0.0.201401110801 [30] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.model.application 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts.renderer_1.0.0.201401110801 [32] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.renderer 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing imported package org.slf4j_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-01-11 03:07:06.889
!MESSAGE Bundle org.eclipse.e4.tutorial.contacts.views.details_1.0.0.201401110801 [33] was not resolved.
!SUBENTRY 2 org.eclipse.e4.tutorial.contacts.views.details 2 0 2014-01-11 03:07:06.889
!MESSAGE Missing imported package org.slf4j_0.0.0.

!ENTRY org.eclipse.osgi 4 0 2014-01-11 03:07:06.890
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.AssertionFailedException: null argument:applicationXMI argument missing
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:342)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:238)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:144)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
```

**Comment by toedter** [comment]
That's weird, I just cloned a fresh repo, build it and everything works.
Any hints what could be different in your environment?

**Comment by marmrk** [comment]
I get the same error when running the same product. Is it because it's run outside eclipse? how do you supply applicationXMI?

**Comment by marmrk** [comment]
There are multiple errors in the log saying:
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

That's logical since I'm running the examples with Java SE 6. Is it possible to change the manifest to require 1.6 Java SE?

UPDATE:
I have changed "Bundle-RequiredExecutionEnvironment: JavaSE-1.7" to "Bundle-RequiredExecutionEnvironment: JavaSE-1.6" in
org.eclipse.e4.tutorial.contacts.logging\META-INF\MANIFEST.MF
org.eclipse.e4.tutorial.contacts.model.application\META-INF\MANIFEST.MF

After that, I've rebuilt the modules, and the application run successfully.
